### ISSUE TITLE
DemoView Route conflicting

### ISSUE THREAD

**Issue by Hedath** [rudiejd/vaadin-chartjs#10]
The DemoView is included in the addon, and has an empty route. This route is already in use in our application, so we get an exception during deploy:
[deploy_stacktrace.txt](https://github.com/rudiejd/vaadin-chartjs/files/8514481/deploy_stacktrace.txt)

Could you use a different route? Or it would be even better if this demo would be in another maven module.

**Comment by Charlynux** [comment]
Got the same problem here.

I can't find a way in Vaadin to exclude this class from my application.

@rudiejd
I'll be happy to help you removing this View from the package.
Could we discuss the best strategy for this ?

**Comment by rudiejd** [comment]
Hi, sorry for the late response. I think @Hedath is correct - this demo should be in another Maven module.

**Comment by rudiejd** [comment]
This should be fixed in the current version on Vaadin directory.

**Comment by rudiejd** [comment]
https://github.com/rudiejd/vaadin-chartjs/commit/36687924c9b4fd66cc49d97ec4babf72c875d2c0#diff-db7cdefe2cd24605c540e39815999f8f7083f61966dc73b38d059d7d85f43146
