### ISSUE TITLE
The "this" variable is undefined in js script with hotdeploy enabled

### ISSUE THREAD

**Issue by Bethibande** [rudiejd/vaadin-chartjs#11]
### Your issue description
Since Vaadin 24 the Framework the framework started throwing an error when hotdeploy is enabled.
The Details of his Issue including a demo project can be found [here](https://github.com/vaadin/flow/issues/16842).
The above Issue already includes comments stating how to fix the Issue but was closed as this addon is not maintained by Vaadin.
It'd be thankful if this Issue could be resolved in due time.

**Comment by rudiejd** [comment]
Thanks for raising this! Just merged a PR to fix it. Sorry for the late response - haven't taken a look at this project, or anything Vaadin related, in a while.
